name: Build APK

on:
  push:
    branches:
      - build-app
  pull_request:
    branches:
      - build-app

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Build Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.cache/pip
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer

      - name: Install Buildozer Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake \
            libffi-dev libssl-dev automake
          python3 -m pip install --upgrade --user Cython virtualenv
          python3 -m pip install --upgrade --user buildozer

      - name: Set up Java 17 (for Android build tools)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK with Buildozer
        run: |
          export PATH=$HOME/.local/bin:$PATH
          # Adjust path if your main.py and buildozer.spec are in a subfolder
          # If everything is in root, comment out this cd line
          # cd frontend
          yes | buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
